/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import koneksi.koneksi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author achyar
 */
public class formUtama extends javax.swing.JFrame {

    Statement stt;
    Statement stt2;
    ResultSet rss;
    DefaultTableModel model;
    String tgl;
    public formUtama() {
        initComponents();
        jPanel1.setVisible(true);
        makanan.setVisible(false);
        transaksi.setVisible(false);
        tabel_makanan();
        tampil_tabel();
        tabel_transaksi();
        tampil_tabel_transaksi();
        tglskrg();
        no_transaksi();
        kode_makanan();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        makanan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_makan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_ket = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_makanan = new javax.swing.JTable();
        transaksi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_admin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_no_trx = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        combo_paket = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_paket = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_harga_paket = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        btn_beli = new javax.swing.JButton();
        btn_hapus_trx = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_nama_admin = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel15.setText("Fast Food");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel15)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel15)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("PAKET MAKANAN");

        jLabel2.setText("Kode Paket");

        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Makanan");

        jLabel4.setText("Harga");

        jLabel5.setText("Keterangan");

        txt_area_ket.setColumns(20);
        txt_area_ket.setRows(5);
        jScrollPane1.setViewportView(txt_area_ket);

        btn_save.setText("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table_makanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_makananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_makanan);

        javax.swing.GroupLayout makananLayout = new javax.swing.GroupLayout(makanan);
        makanan.setLayout(makananLayout);
        makananLayout.setHorizontalGroup(
            makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makananLayout.createSequentialGroup()
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(makananLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(52, 52, 52)
                            .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_kode)
                                .addComponent(txt_makan)
                                .addComponent(txt_harga)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                        .addGroup(makananLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(btn_save)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makananLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(75, 75, 75)))
                    .addGroup(makananLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makananLayout.setVerticalGroup(
            makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makananLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_makan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(makanan, "card3");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Menu Transaksi");

        jLabel7.setText("Kasir");

        txt_id_admin.setEditable(false);
        txt_id_admin.setEnabled(false);
        txt_id_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_adminActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal Transaksi");

        txt_tgl.setEditable(false);

        jLabel9.setText("No Transaksi");

        txt_no_trx.setEditable(false);

        btn_next.setText("Transaksi Selanjutnya...");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel10.setText("Kode Paket");

        combo_paket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_paketItemStateChanged(evt);
            }
        });

        jLabel11.setText("Nama Paket");

        txt_paket.setEditable(false);

        jLabel12.setText("Harga Paket");

        txt_harga_paket.setEditable(false);

        jLabel13.setText("Jumlah");

        txt_jumlah.setText("1");

        btn_beli.setText("Beli");
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });

        btn_hapus_trx.setText("Hapus");
        btn_hapus_trx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_trxActionPerformed(evt);
            }
        });

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_transaksi);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("Total");

        txt_total.setEditable(false);

        txt_nama_admin.setEditable(false);

        jButton3.setText("Cetak Struk");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaksiLayout.createSequentialGroup()
                                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tgl)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiLayout.createSequentialGroup()
                                        .addComponent(txt_no_trx)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(transaksiLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(transaksiLayout.createSequentialGroup()
                                        .addComponent(txt_id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_nama_admin))))
                            .addGroup(transaksiLayout.createSequentialGroup()
                                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(67, 67, 67)
                                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_harga_paket)
                                        .addComponent(txt_jumlah)
                                        .addGroup(transaksiLayout.createSequentialGroup()
                                            .addComponent(btn_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                            .addComponent(btn_hapus_trx, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_paket))
                                    .addComponent(combo_paket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator1)))
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(transaksiLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_no_trx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_harga_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_beli)
                    .addComponent(btn_hapus_trx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(transaksi, "card4");

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Makanan");

        jMenuItem2.setText("Daftar Paket");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        jMenuItem3.setText("Transaksi Penjualan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        login lgn = new login();
        this.setVisible(false);
        lgn.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = koneksi.getConnection();
        int row = table_makanan.getSelectedRow();
        try {
            stt = con.createStatement();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Mohon pilih tabel terlebih dahulu","Pesan",JOptionPane.WARNING_MESSAGE);
            }
            else{
                String sql = "UPDATE paket SET paket_nama = '"+txt_makan.getText()+"'"
                        + ", paket_keterangan = '"+txt_area_ket.getText()+"', paket_harga = '"+txt_harga.getText()+"' WHERE paket_kode = '"+txt_kode.getText()+"'";
                stt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil Diubah");
                tabel_makanan();
                tampil_tabel();
                clear();
                btn_save.setText("Simpan");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanel1.setVisible(false);
        makanan.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        kode_makanan();
        transaksi.setVisible(true);
       makanan.setVisible(false);
       jPanel1.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Connection con = koneksi.getConnection();
        try {
         if(btn_save.getText().equals("Batal")){
             clear();
             btn_save.setText("Simpan");
         }
         else{
            if(txt_kode.getText().equals("")||txt_makan.getText().equals("")||txt_area_ket.getText().equals("")||txt_harga.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Mohon diisi data yang kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            }
            else{    
            stt = con.createStatement();
            String sql = "INSERT INTO paket VALUES('"+txt_kode.getText()+"', '"+txt_makan.getText()+"','"+txt_area_ket.getText()+"','"+txt_harga.getText()+"')";   
            stt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
            tabel_makanan();
            tampil_tabel();
            clear();
           }
         }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void table_makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_makananMouseClicked
        int row = table_makanan.getSelectedRow();
        txt_kode.setText(table_makanan.getValueAt(row, 0).toString());
        txt_makan.setText(table_makanan.getValueAt(row, 1).toString());
        txt_area_ket.setText(table_makanan.getValueAt(row, 2).toString());
        txt_harga.setText(table_makanan.getValueAt(row, 3).toString());
        txt_kode.setEnabled(false);
        btn_save.setText("Batal");
    }//GEN-LAST:event_table_makananMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = koneksi.getConnection();
        int row = table_makanan.getSelectedRow();
        try {
            stt = con.createStatement();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Mohon pilih tabel terlebih dahulu","Pesan",JOptionPane.WARNING_MESSAGE);
            }
            else{
                String sql = "DELETE FROM paket WHERE paket_kode = '"+txt_kode.getText()+"'";
                stt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                tabel_makanan();
                tampil_tabel();
                clear();
                btn_save.setText("Simpan");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        no_transaksi();
        tabel_transaksi();
        tampil_tabel_transaksi();
        txt_total.setText("");
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
       Connection con = koneksi.getConnection();
        if(txt_jumlah.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data tidak boleh kosong");
        } else {
            int total = Integer.parseInt(txt_harga_paket.getText()) * Integer.parseInt(txt_jumlah.getText());
            int simpan2 = 0;
            if(txt_total.getText().equals("")){
                simpan2 = 0;
            }
            else
                simpan2 = Integer.valueOf(txt_total.getText());

            String sql2 = "INSERT INTO detil_transaksi(transaksi_id, paket_kode, detil_transaksi_harga, detil_transaksi_jumlah, detil_transaksi_total) VALUES('"+txt_no_trx.getText()+"','"+combo_paket.getSelectedItem().toString()+"','"+txt_harga_paket.getText()+"','"+txt_jumlah.getText()+"','"+total+"')";
            try {
                    simpan_no();
                    stt2 = con.createStatement();
                    stt2.executeUpdate(sql2);
                    txt_total.setText(String.valueOf(simpan2+total));
                    tabel_transaksi();
                    tampil_tabel_transaksi();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_beliActionPerformed

    private void btn_hapus_trxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_trxActionPerformed
        Connection con = koneksi.getConnection();
        int row = table_transaksi.getSelectedRow();
        try {
            stt = con.createStatement();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Anda Belum Memilih Tabel");
            }
            else{
                int harga = Integer.parseInt((String) table_transaksi.getModel().getValueAt(row, 5));
                int total = Integer.parseInt(txt_total.getText());
                String sql = "DELETE FROM detil_transaksi WHERE detil_transaksi_id = '"+table_transaksi.getModel().getValueAt(row, 0)+"'";
                stt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                txt_total.setText(String.valueOf(total-harga));
                tabel_transaksi();
                tampil_tabel_transaksi();
                clear();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapus_trxActionPerformed

    private void combo_paketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_paketItemStateChanged
        Connection con = koneksi.getConnection();
        ResultSet rss2;
        String sql = "SELECT * FROM paket WHERE paket_kode = '"+combo_paket.getSelectedItem().toString()+"'";
        try {
            stt = con.createStatement();
            rss2 = stt.executeQuery(sql);
            if(rss2.next()){
                txt_paket.setText(rss2.getString("paket_nama"));
                txt_harga_paket.setText(rss2.getString("paket_harga"));
            }
            rss2.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_combo_paketItemStateChanged

    private void txt_id_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_adminActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = koneksi.getConnection();
            String NamaFile = "/laporan/struk_pembayaran.jasper";
            HashMap hash = new HashMap();
        try {
            hash.put("idtransaksi", txt_no_trx.getText());
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed
    public JTextField pengguna_id(){
        return txt_id_admin;
    }
    
    public JTextField pengguna_nama(){
        return txt_nama_admin;
    }
    
    public void clear(){
    txt_harga.setText("");
    txt_kode.setText("");
    txt_area_ket.setText("");
    txt_makan.setText("");
    txt_kode.setEnabled(true);
    }
    
    public void tglskrg(){
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
        SimpleDateFormat format2= new SimpleDateFormat("yyyy-MM-dd");
        tgl = format2.format(skrg);
        txt_tgl.setText(format.format(skrg));
    }
    public void no_transaksi(){
        Connection con = koneksi.getConnection();
        String sql = "SELECT transaksi_id FROM transaksi";
        try {
            stt = con.createStatement();
            rss = stt.executeQuery(sql);
            if(rss.last()){
                txt_no_trx.setText(String.valueOf(rss.getInt(1)+1));
            }
            else
                txt_no_trx.setText("1");
        } catch (Exception e) {
        }
    }
    public void kode_makanan(){
        Connection con = koneksi.getConnection();
        String sql = "SELECT * FROM paket";
        try {
         stt = con.createStatement();
         rss= stt.executeQuery(sql);
         while(rss.next()){
             combo_paket.addItem(rss.getString("paket_kode"));
         }
        } catch (Exception e) {
        }
    }
    
    private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {                                  
char c = evt.getKeyChar();
if (!((c >= '0') && (c <= '9') && txt_harga_paket.getText().length() < 10
|| (c == KeyEvent.VK_BACK_SPACE)
|| (c == KeyEvent.VK_DELETE))) {
getToolkit().beep();
evt.consume();
}
}                                 

private void txt_jumlah_tKeyTyped(java.awt.event.KeyEvent evt) {                                      
char c = evt.getKeyChar();
if (!((c >= '0') && (c <= '9') && txt_jumlah.getText().length() < 10
|| (c == KeyEvent.VK_BACK_SPACE)
|| (c == KeyEvent.VK_DELETE))) {
getToolkit().beep();
evt.consume();
}
} 

    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = koneksi.getConnection();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }

    public void simpan_no(){
    Connection con = koneksi.getConnection();
        String sql = "INSERT INTO transaksi VALUES('"+txt_no_trx.getText()+"','"+txt_id_admin.getText()+"','"+tgl+"')";
        try {
            stt = con.createStatement();
            stt.executeUpdate(sql);
        } catch (Exception e) {
        }
    }
    
    private void tabel_makanan(){
        model = new DefaultTableModel();
        table_makanan.setModel(model);
        model.addColumn("Kode Paket");
        model.addColumn("Nama Makanan");
        model.addColumn("Keterangan Paket");
        model.addColumn("Harga");
    }
    
    private void tabel_transaksi(){
        model = new DefaultTableModel();
        table_transaksi.setModel(model);
        model.addColumn("Id");
        model.addColumn("No Transaksi");
        model.addColumn("Paket");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total");
    }
    
    private void tampil_tabel(){
       Connection con = koneksi.getConnection();
       try {
           stt = con.createStatement();
           String sql = "SELECT * FROM paket";
           rss = stt.executeQuery(sql);
           while(rss.next()){
               Object[] data;
               data = new Object[4];
               data[0] = rss.getString("paket_kode");
               data[1] = rss.getString("paket_nama");
               data[2] = rss.getString("paket_keterangan");
               data[3] = rss.getString("paket_harga");
               model.addRow(data);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    
    private void tampil_tabel_transaksi(){
       Connection con = koneksi.getConnection();
       try {
           stt = con.createStatement();
           String sql = "SELECT * FROM detil_transaksi WHERE transaksi_id = '"+txt_no_trx.getText()+"'";
           rss = stt.executeQuery(sql);
           while(rss.next()){
               Object[] data;
               data = new Object[6];
               data[0] = rss.getString(1);
               data[1] = rss.getString(2);
               data[2] = rss.getString(3);
               data[3] = rss.getString(4);
               data[4] = rss.getString(5);
               data[5] = rss.getString(6);
               model.addRow(data);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_beli;
    private javax.swing.JButton btn_hapus_trx;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_paket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel makanan;
    private javax.swing.JTable table_makanan;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JPanel transaksi;
    private javax.swing.JTextArea txt_area_ket;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_harga_paket;
    private javax.swing.JTextField txt_id_admin;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_makan;
    private javax.swing.JTextField txt_nama_admin;
    private javax.swing.JTextField txt_no_trx;
    private javax.swing.JTextField txt_paket;
    private javax.swing.JTextField txt_tgl;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

}
